treatments:
  - name: solo
    factorIds:
      - yLgJTwkJB3dh4jh3r
      - A6nriq6uaerSLGxv2
      - hEQNn39WugmZNGK3y
      - iZyssrDWEYhnc8Q7B
      - RhXZkZdj5fYbQNssb
      - nNqv434CrsBRjkPLE
      - XhGgGb3Kne64v8DgZ
    archivedAt: 2023-12-21T04:57:39.787Z
  - name: team
    factorIds:
      - DjKCDtyNpyHu7XvP9
      - A6nriq6uaerSLGxv2
      - hEQNn39WugmZNGK3y
      - iZyssrDWEYhnc8Q7B
      - RhXZkZdj5fYbQNssb
      - nNqv434CrsBRjkPLE
      - XhGgGb3Kne64v8DgZ
    archivedAt: 2023-12-21T04:57:40.168Z
  - name: preTest
    factorIds:
      - yLgJTwkJB3dh4jh3r
      - A6nriq6uaerSLGxv2
      - hEQNn39WugmZNGK3y
      - t8JscYzadj76bngCD
      - tXtK9D88FvXWay7kQ
      - nNqv434CrsBRjkPLE
      - 5hXH4dva8NDRMEb4t
      - JExpCkDteCwhQFFNz
  - name: postTest
    factorIds:
      - yLgJTwkJB3dh4jh3r
      - A6nriq6uaerSLGxv2
      - hEQNn39WugmZNGK3y
      - t8JscYzadj76bngCD
      - tXtK9D88FvXWay7kQ
      - nNqv434CrsBRjkPLE
      - 5hXH4dva8NDRMEb4t
      - 6rpCWj2XmviQk8Smu
factorTypes:
  - _id: qqBJ7jeruPJFb37it
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: ZzHiS2M4TFGPQRPsL
    name: stageDuration
    description: Specifies how many seconds for each decision stage
    required: false
    type: Integer
    min: 5
    max: 1000
  - _id: YuxymxgdicnLpwqQq
    name: stepOne
    description: SequenceOne of 5 tasks or SequenceTwo of 5 tasks
    required: true
    type: Boolean
  - _id: rfisFt6sGMhs7FN4P
    name: taskOrder
    description: How to do the sequence to be ordered
    required: false
    type: String
    archivedAt: 2018-10-15T17:22:05.622Z
  - _id: K5zoaut98tuZsmpa7
    name: basePay
    description: 'The amount for base pay (i.e., showing up and completing the experiment)'
    required: false
    type: Number
    min: 0
    max: 1
  - _id: CgCzQdbcMNh6JqAZT
    name: conversionRate
    description: This will be multiplied by their total score to compute the bonus
    required: false
    type: Number
    min: 0
    max: 10
  - _id: 9HMtrxYDhvFhhcrzM
    name: optimalSolutionBonus
    description: 'For each optimal solution, what is the additional bonus? (in dollars)'
    required: false
    type: Number
    min: 0
    max: 10
  - _id: gyMzogFBfCYjqZmz3
    name: shuffleTaskOrder
    description: How to do the sequence to be ordered
    required: false
    type: Boolean
  - _id: xTpcJ8Kx9N5BSqm5b
    name: experimentPhase
    description: >-
      Which phase of the coding task experiment is being conducted (preTest or
      postTest).
    required: true
    type: String
    min: 0
    max: 100
factors:
  - _id: K5CcaREfjW2x7aSMa
    name: 'true'
    value: true
    factorTypeId: YuxymxgdicnLpwqQq
  - _id: hEQNn39WugmZNGK3y
    name: 'false'
    value: false
    factorTypeId: YuxymxgdicnLpwqQq
  - _id: XhGgGb3Kne64v8DgZ
    name: 'true'
    value: true
    factorTypeId: gyMzogFBfCYjqZmz3
  - _id: 5hXH4dva8NDRMEb4t
    name: 'false'
    value: false
    factorTypeId: gyMzogFBfCYjqZmz3
  - _id: yLgJTwkJB3dh4jh3r
    name: solo
    value: 1
    factorTypeId: qqBJ7jeruPJFb37it
  - _id: DjKCDtyNpyHu7XvP9
    name: team
    value: 3
    factorTypeId: qqBJ7jeruPJFb37it
  - _id: A6nriq6uaerSLGxv2
    name: 5min
    value: 300
    factorTypeId: ZzHiS2M4TFGPQRPsL
  - _id: t8JscYzadj76bngCD
    name: none
    value: 0
    factorTypeId: K5zoaut98tuZsmpa7
  - _id: iZyssrDWEYhnc8Q7B
    name: oneDollar
    value: 1
    factorTypeId: K5zoaut98tuZsmpa7
  - _id: tXtK9D88FvXWay7kQ
    name: none
    value: 0
    factorTypeId: CgCzQdbcMNh6JqAZT
  - _id: RhXZkZdj5fYbQNssb
    name: small
    value: 0.00001
    factorTypeId: CgCzQdbcMNh6JqAZT
  - _id: nNqv434CrsBRjkPLE
    name: 50cents
    value: 0.5
    factorTypeId: 9HMtrxYDhvFhhcrzM
  - _id: JExpCkDteCwhQFFNz
    name: preTest
    value: preTest
    factorTypeId: xTpcJ8Kx9N5BSqm5b
  - _id: 6rpCWj2XmviQk8Smu
    name: postTest
    value: postTest
    factorTypeId: xTpcJ8Kx9N5BSqm5b
lobbyConfigs:
  - timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
